### ISSUE TITLE
Maker Coin is not available in my region

### ISSUE THREAD

**Issue by titus123abc123** [Kenshiro-28/GDAX-Trading-Bot#2]
The bot keeps erroring out because maker coin is not available in my region. How can I change it to use another coin? Thanks

`'content-length': '40',
      connection: 'close',
      'set-cookie': [Array],
      'access-control-allow-headers': 'Content-Type, Accept, cb-session, cb-fp, cb-form-factor',
      'access-control-allow-methods': 'GET,POST,DELETE,PUT',
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'cb-before, cb-after, cb-gdpr',
      'access-control-max-age': '7200',
      'cache-control': 'no-store',
      etag: 'W/"28-joNo1vUjXexHVk2DKyHP4jUG9Fs"',
      'strict-transport-security': 'max-age=15552000; includeSubDomains',
      'x-content-type-options': 'nosniff',
      'x-dns-prefetch-control': 'off',
      'x-download-options': 'noopen',
      'x-frame-options': 'SAMEORIGIN',
      'x-xss-protection': '1; mode=block',
      'cf-cache-status': 'DYNAMIC',
      'cf-request-id': '0774528eac00000cb967a10000000001',
      'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
      server: 'cloudflare',
      'cf-ray': '60cd86c448ea0cb9-EWR'
    },
    rawHeaders: [
      'Date',
      'Tue, 05 Jan 2021 13:25:38 GMT',
      'Content-Type',
      'application/json; charset=utf-8',
      'Content-Length',
      '40',
      'Connection',
      'close',
      'Set-Cookie',
      '__cfduid=d62392c99b226d63088bc4bc482ebec351609853138; expires=Thu, 04-Feb-21 13:25:38 GMT; path=/; domain=.pro.coinbase.com; HttpOnly; SameSite=Lax',
      'Access-Control-Allow-Headers',
      'Content-Type, Accept, cb-session, cb-fp, cb-form-factor',
      'Access-Control-Allow-Methods',
      'GET,POST,DELETE,PUT',
      'Access-Control-Allow-Origin',
      '*',
      'Access-Control-Expose-Headers',
      'cb-before, cb-after, cb-gdpr',
      'Access-Control-Max-Age',
      '7200',
      'Cache-Control',
      'no-store',
      'Etag',
      'W/"28-joNo1vUjXexHVk2DKyHP4jUG9Fs"',
      'Strict-Transport-Security',
      'max-age=15552000; includeSubDomains',
      'X-Content-Type-Options',
      'nosniff',
      'X-Dns-Prefetch-Control',
      'off',
      'X-Download-Options',
      'noopen',
      'X-Frame-Options',
      'SAMEORIGIN',
      'X-Xss-Protection',
      '1; mode=block',
      'CF-Cache-Status',
      'DYNAMIC',
      'cf-request-id',
      '0774528eac00000cb967a10000000001',
      'Expect-CT',
      'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
      'Server',
      'cloudflare',
      'CF-RAY',
      '60cd86c448ea0cb9-EWR'
    ],
    trailers: {},
    rawTrailers: [],
    aborted: false,
    upgrade: false,
    url: '',
    method: null,
    statusCode: 400,
    statusMessage: 'Bad Request',
    client: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'api.pro.coinbase.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.pro.coinbase.com',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [ClientRequest],
      timeout: 10000,
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 25294,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: 10000,
        _idlePrev: [TimersList],
        _idleNext: [Timeout],
        _idleStart: 2121788,
        _onTimeout: [Function: bound ],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: false,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 25305,
        [Symbol(triggerId)]: 25303
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _consuming: false,
    _dumped: false,
    req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'POST /orders HTTP/1.1\r\n' +
        'User-Agent: coinbase-pro-node-client\r\n' +
        'Accept: application/json\r\n' +
        'Content-Type: application/json\r\n' +
        'CB-ACCESS-KEY: ac8b04e0d5a0c8a1655541f1ad73b4f1\r\n' +
        'CB-ACCESS-SIGN: 2UT/mfMddCw3WGjxG7+uUG3vLcW+PUeFUDHcE7ZKp3I=\r\n' +
        'CB-ACCESS-TIMESTAMP: 1609853137.102\r\n' +
        'CB-ACCESS-PASSPHRASE: coukwn27hww\r\n' +
        'host: api.pro.coinbase.com\r\n' +
        'content-length: 67\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/orders',
      _ended: true,
      res: [Circular *1],
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.pro.coinbase.com',
      protocol: 'https:',
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    request: Request {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      body: '{"size":"0.01","product_id":"MKR-BTC","type":"market","side":"buy"}',
      headers: [Object],
      method: 'POST',
      uri: [Url],
      qsStringifyOptions: [Object],
      timeout: 10000,
      callback: [Function (anonymous)],
      readable: true,
      writable: true,
      explicitMethod: true,
      _qs: [Querystring],
      _auth: [Auth],
      _oauth: [OAuth],
      _multipart: [Multipart],
      _redirect: [Redirect],
      _tunnel: [Tunnel],
      setHeader: [Function (anonymous)],
      hasHeader: [Function (anonymous)],
      getHeader: [Function (anonymous)],
      removeHeader: [Function (anonymous)],
      localAddress: undefined,
      pool: {},
      dests: [],
      __isRequestRequest: true,
      _callback: [Function (anonymous)],
      proxy: null,
      tunnel: true,
      setHost: true,
      originalCookieHeader: undefined,
      _disableCookies: true,
      _jar: undefined,
      port: 443,
      host: 'api.pro.coinbase.com',
      path: '/orders',
      httpModule: [Object],
      agentClass: [Function: Agent],
      agent: [Agent],
      _started: true,
      href: 'https://api.pro.coinbase.com/orders',
      req: [ClientRequest],
      ntick: true,
      timeoutTimer: null,
      response: [Circular *1],
      originalHost: 'api.pro.coinbase.com',
      originalHostHeaderName: 'host',
      responseContent: [Circular *1],
      _destdata: true,
      _ended: true,
      _callbackCalled: true,
      [Symbol(kCapture)]: false
    },
    toJSON: [Function: responseToJSON],
    caseless: Caseless { dict: [Object] },
    body: '{"message":"Trading pair not available"}',
    [Symbol(kCapture)]: false,
    [Symbol(RequestTimeout)]: undefined
  },
  data: { message: 'Trading pair not available' }
}`

**Comment by Kenshiro-28** [comment]
Until Maker is available in your region you can use the version 7.05. It trades Tezos instead of Maker :)

**Comment by rijotech** [comment]
XTZ/BTC trading is not yet available in your region.
there is any way we can trade other crypto currencies?

**Comment by Kenshiro-28** [comment]
@rijotech then try version 7.04. It trades Dash and Ethereum :)

**Comment by titus123abc123** [comment]
i actually was able to modify it to trade ltc. open index.js in notepad ++. then control f, find and replace MKR with LTC, MAKER with LITE, maker with lite, Maker with Lite, and Makercoin with LItecoin. then the min seed for litecoin is 0.1 instead of 0.01. it works for me and has been making trades it ltc. good luck
